export enum ACCOUNT_ACTION_TYPES {
    LOGIN = "ACCOUNT:LOGIN",
    LOGOUT = "ACCOUNT:LOGOUT",
    REGISTER = "ACCOUNT:REGISTER",
    LOAD_USER = "ACCOUNT:LOAD_USER",
    SET_AUTH = "ACCOUNT:SET_AUTH",
    SET_LOADING = "ACCOUNT:SET_LOADING",
}